window.FUND_ASSISTANT_DATA = {
  generatedAt: "2026-07-03",
  sources: [
    { group: "官方政策", name: "中国政府网政策文件库", url: "https://sousuo.www.gov.cn/zcwjk/policyDocumentLibrary", weight: 100 },
    { group: "官方政策", name: "国家发改委", url: "https://www.ndrc.gov.cn/", weight: 95 },
    { group: "官方政策", name: "工信部", url: "https://www.miit.gov.cn/", weight: 95 },
    { group: "官方政策", name: "财政部", url: "https://www.mof.gov.cn/", weight: 90 },
    { group: "官方政策", name: "中国人民银行", url: "https://www.pbc.gov.cn/", weight: 95 },
    { group: "资本市场", name: "中国证监会", url: "https://www.csrc.gov.cn/", weight: 95 },
    { group: "统计数据", name: "国家统计局", url: "https://www.stats.gov.cn/", weight: 90 },
    { group: "交易公告", name: "上海证券交易所", url: "https://www.sse.com.cn/", weight: 88 },
    { group: "交易公告", name: "深圳证券交易所", url: "https://www.szse.cn/", weight: 88 },
    { group: "新闻辅助", name: "新华社", url: "https://www.news.cn/", weight: 82 },
    { group: "新闻辅助", name: "证券时报", url: "https://www.stcn.com/", weight: 76 },
    { group: "新闻辅助", name: "中国证券报", url: "https://www.cs.com.cn/", weight: 76 }
  ],
  sectors: [
    {
      id: "broad",
      name: "宽基指数",
      style: "核心底仓",
      score: 78,
      trend: 2,
      action: "分批配置",
      policy: 77,
      money: 84,
      prosperity: 70,
      valuation: 76,
      technical: 72,
      risk: 8,
      funds: ["沪深300ETF联接", "中证500ETF联接", "中证A500指数基金", "创业板ETF联接"],
      signals: ["中长期资金入市政策表述增强", "宽基 ETF 是稳定资金最容易落地的方向", "适合作为组合底仓"],
      risks: ["短期指数波动", "权重行业拖累"]
    },
    {
      id: "dividend",
      name: "红利低波",
      style: "稳健防守",
      score: 75,
      trend: 0,
      action: "持有/定投",
      policy: 68,
      money: 80,
      prosperity: 70,
      valuation: 78,
      technical: 67,
      risk: 6,
      funds: ["红利低波ETF联接", "央企红利ETF联接", "中证红利指数基金"],
      signals: ["低利率环境提升高股息资产吸引力", "险资和长期资金偏好稳定现金流"],
      risks: ["交易拥挤", "煤炭银行等权重行业调整"]
    },
    {
      id: "ai",
      name: "AI算力/半导体",
      style: "科技成长",
      score: 82,
      trend: 4,
      action: "小额分批",
      policy: 90,
      money: 78,
      prosperity: 82,
      valuation: 58,
      technical: 86,
      risk: 18,
      funds: ["人工智能ETF联接", "云计算ETF联接", "半导体ETF联接", "通信ETF联接"],
      signals: ["算力基础设施、数据要素、国产替代政策方向清晰", "行业弹性大，适合控制仓位分批参与"],
      risks: ["估值波动", "海外限制", "主题过热"]
    },
    {
      id: "advanced",
      name: "高端制造/机器人",
      style: "中长期成长",
      score: 80,
      trend: 3,
      action: "定投观察",
      policy: 88,
      money: 72,
      prosperity: 78,
      valuation: 66,
      technical: 80,
      risk: 13,
      funds: ["机器人ETF联接", "高端制造主题基金", "工业母机ETF联接"],
      signals: ["制造业升级、设备更新、机器人产业政策共振", "订单和业绩兑现是关键"],
      risks: ["业绩兑现慢", "主题轮动快"]
    },
    {
      id: "medicine",
      name: "医药创新/医疗器械",
      style: "修复成长",
      score: 67,
      trend: 1,
      action: "观察低吸",
      policy: 65,
      money: 61,
      prosperity: 70,
      valuation: 72,
      technical: 58,
      risk: 12,
      funds: ["医药ETF联接", "创新药ETF联接", "医疗器械ETF联接"],
      signals: ["估值处在相对修复区间", "创新药出海和器械国产化值得跟踪"],
      risks: ["集采政策", "研发失败", "资金关注度不足"]
    },
    {
      id: "consumption",
      name: "消费/食品饮料",
      style: "复苏弹性",
      score: 61,
      trend: -1,
      action: "等待确认",
      policy: 63,
      money: 54,
      prosperity: 58,
      valuation: 68,
      technical: 50,
      risk: 10,
      funds: ["消费ETF联接", "食品饮料指数基金", "家电ETF联接"],
      signals: ["以扩内需和消费政策为主要触发", "需要销售数据和居民收入预期改善"],
      risks: ["复苏不及预期", "白酒估值修复不稳定"]
    },
    {
      id: "newenergy",
      name: "新能源/储能",
      style: "困境反转",
      score: 58,
      trend: 1,
      action: "轻仓跟踪",
      policy: 78,
      money: 50,
      prosperity: 55,
      valuation: 70,
      technical: 47,
      risk: 16,
      funds: ["新能源车ETF联接", "光伏ETF联接", "储能主题基金"],
      signals: ["长期政策仍支持绿色转型", "等待产能出清和价格企稳"],
      risks: ["产能过剩", "价格战", "海外贸易摩擦"]
    },
    {
      id: "fixed",
      name: "债券/固收+",
      style: "现金管理",
      score: 73,
      trend: 0,
      action: "底仓配置",
      policy: 72,
      money: 74,
      prosperity: 66,
      valuation: 76,
      technical: 70,
      risk: 5,
      funds: ["货币基金", "中短债基金", "纯债基金", "稳健固收+基金"],
      signals: ["适合波动控制和等待权益市场机会", "利率变化决定久期选择"],
      risks: ["利率上行", "信用风险", "固收+权益仓波动"]
    }
  ],
  markets: [
    {
      id: "a-share",
      market: "A股",
      name: "国内大A",
      score: 74,
      trend: 2,
      action: "宽基底仓 + 主题分批",
      drivers: ["国内政策托底", "中长期资金入市", "人民币资产估值修复"],
      funds: ["沪深300ETF联接", "中证A500指数基金", "中证500ETF联接", "科创50ETF联接"],
      risks: ["政策兑现慢", "成交量不足", "地产链和消费修复偏弱"]
    },
    {
      id: "hongkong",
      market: "港股",
      name: "港股",
      score: 70,
      trend: 2,
      action: "低估值分批，控制波动",
      drivers: ["南向资金", "互联网平台估值修复", "美债利率回落时弹性更大"],
      funds: ["恒生科技ETF联接", "恒生互联网ETF联接", "港股通红利指数基金"],
      risks: ["美元利率扰动", "流动性折价", "互联网监管预期波动"]
    },
    {
      id: "us",
      market: "美股",
      name: "美股",
      score: 76,
      trend: 1,
      action: "已有持仓持有，新仓避免追高",
      drivers: ["AI资本开支", "美元流动性", "大型科技盈利韧性"],
      funds: ["纳斯达克100指数(QDII)", "标普500指数(QDII)", "全球科技主题QDII"],
      risks: ["估值拥挤", "汇率波动", "美联储路径变化"]
    },
    {
      id: "global",
      market: "全球共振",
      name: "全球共同趋势",
      score: 79,
      trend: 3,
      action: "AI/算力链全球映射",
      drivers: ["AI算力", "半导体周期", "低利率交易", "高股息资产"],
      funds: ["半导体ETF联接", "人工智能ETF联接", "纳斯达克100指数(QDII)", "恒生科技ETF联接"],
      risks: ["同向拥挤", "海外限制", "汇率与估值双杀"]
    }
  ],
  globalLinks: [
    "美股 AI 和半导体上涨，通常会带动 A 股半导体、算力、通信设备和港股互联网情绪。",
    "美债利率下行时，港股和成长股更容易修复；利率上行时，红利低波和债券仓位更重要。",
    "人民币走强时，外资和港股弹性更好；人民币走弱时，QDII 和美元资产有对冲价值。",
    "全球风险偏好转弱时，先看现金、短债、红利，再等宽基和科技回撤后的分批机会。"
  ],
  alipayPicks: {
    date: "2026-07-03",
    stance: "分批加购，不追单日大涨",
    note: "支付宝里优先搜基金类型和指数关键词，再按规模、费率、跟踪误差、成立时间和历史回撤筛选。以下为基金方向建议，不是收益承诺。",
    items: [
      {
        rank: 1,
        name: "中证A500 / 沪深300 指数基金",
        market: "A股",
        action: "优先补仓",
        buy: "今日可小额加购 1 份，后续跌 1.5%-2.5% 再补 1 份",
        search: ["中证A500指数", "沪深300ETF联接", "沪深300指数增强"],
        reason: "A 股底仓方向，政策和中长期资金入市更容易先落到宽基。",
        maxWeight: "组合 25%-35%",
        avoid: "若当天大涨超过 2%，改为观望。"
      },
      {
        rank: 2,
        name: "恒生科技 / 港股互联网联接",
        market: "港股",
        action: "弹性加购",
        buy: "适合分 3-5 次买，不一次买满",
        search: ["恒生科技ETF联接", "港股互联网", "恒生互联网"],
        reason: "港股估值弹性大，受美债利率和南向资金影响，适合作为进攻仓。",
        maxWeight: "组合 10%-15%",
        avoid: "若已有港股仓超过 20%，今日不加。"
      },
      {
        rank: 3,
        name: "半导体 / 人工智能 / 算力主题",
        market: "A股",
        action: "只低吸",
        buy: "只在回调日小额买，红盘急涨不追",
        search: ["半导体ETF联接", "人工智能ETF联接", "云计算ETF联接", "通信ETF联接"],
        reason: "全球 AI 趋势仍在，但主题拥挤，适合小仓位捕捉弹性。",
        maxWeight: "组合 8%-12%",
        avoid: "若近 5 日连续上涨，暂停。"
      },
      {
        rank: 4,
        name: "纳斯达克100 / 标普500 QDII",
        market: "美股",
        action: "持有为主",
        buy: "已有仓位先不追，缺美股配置可小额定投",
        search: ["纳斯达克100指数QDII", "标普500指数QDII", "全球科技QDII"],
        reason: "美股长期质量高，但 AI 和半导体短线波动加大。",
        maxWeight: "组合 10%-20%",
        avoid: "若支付宝显示估值高位或溢价明显，等待。"
      },
      {
        rank: 5,
        name: "中短债 / 货币基金",
        market: "债券/货币",
        action: "保留弹药",
        buy: "不确定时先买短债或货币，等权益回调再切",
        search: ["中短债", "短债债券", "货币基金", "同业存单指数"],
        reason: "用于降低波动和保留补仓资金。",
        maxWeight: "组合 20%-40%",
        avoid: "若你已满仓债券且权益仓很低，不需要继续加。"
      }
    ]
  },
  report: {
    date: "2026-07-03",
    marketMood: "中性偏积极",
    summary: "今日建议以宽基补仓为主，港股和科技主题只做小额弹性仓，美股 QDII 以持有和定投为主，短债/货币保留补仓资金。",
    actions: [
      { level: "稳健型", text: "50% 债券/货币 + 30% 宽基 + 20% 红利低波，暂不追逐高波动主题。" },
      { level: "均衡型", text: "30% 债券/货币 + 35% 宽基 + 20% 红利低波 + 15% 科技/制造主题。" },
      { level: "进取型", text: "20% 债券/货币 + 35% 宽基 + 25% 科技成长 + 10% 高端制造 + 10% 红利低波，主题仓分三次买入。" }
    ],
    alerts: [
      "单一行业主题基金不建议超过总仓位 20%。",
      "若连续两日行业资金流出且新闻热度过高，暂停追买。",
      "政策利好发布当天不要一次性满仓，优先等待回踩或分批。"
    ]
  }
};
